--- #YAML:1.0
name:                TipJar-MTA
version:             0.32
abstract:            outgoing SMTP with exponential random backoff.
license:             ~
author:              
    - David Nicol <davidnico@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    dateheader:                    0
    Net::DNS:                      0.38
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
