# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TipJar-MTA
version:      0.19
version_from: MTA.pm
installdirs:  site
requires:
    dateheader:                    0
    Net::DNS:                      0.38

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
